server:
  port: 81
spring:
  application:
    name: seata-account
  datasource:
    druid:
      url: jdbc:mysql://192.168.229.128:3306/seata-account?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
#====================================mybatis-plus config=
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.media.*.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
